export const navLinks = [
	{ route: 'direction', name: 'Direction' },
	{ route: 'command', name: 'Command' },
	{ route: 'services', name: 'Services' },
	{ route: 'tools', name: 'Tools' },
	{ route: 'clients', name: 'Clients' },
	{ route: 'portfolio', name: 'Portfolio' },
	{ route: 'language', name: 'Language' },
]

export const lngs = [
	{ route: 'ru', label: 'Рус' },
	{ route: 'en', label: 'Eng' },
]

export const services = [
	{ route: 'mobil', label: 'Development of mobile applications' },
	{ route: 'erp', label: 'Development and implementation ERP systems' },
	{ route: 'design', label: 'User interface, User experience design' },
	{ route: 'optimization', label: 'Optimization IT consulting infrastructure' },
	{ route: 'consulting', label: 'IT consulting' },
]

export const portfolio = [
	{ route: 'delever', label: 'Delever' },
	{ route: 'sms', label: 'Sms.uz' },
	{ route: 'goodzone', label: 'Goodzone' },
	{ route: 'iman', label: 'Iman' },
]

export const tools = [
	{ label: 'Promotheus', cn: 'Devops' },
	{ label: 'Loki', cn: 'Devops' },
	{ label: 'Bitbucket', cn: 'Devops' },
	{ label: 'Gitlab', cn: 'Devops' },
	{ label: 'Kotlin', cn: 'Mobile' },
	{ label: 'Android', cn: 'Mobile' },
	{ label: 'Java', cn: 'Mobile' },
	{ label: 'Azure', cn: 'Infrastructure' },
	{ label: 'GCP', cn: 'Infrastructure' },
	{ label: 'DigitalOcean', cn: 'Infrastructure' },
	{ label: 'AWS', cn: 'Infrastructure' },
	{ label: 'Kubernetes', cn: 'Infrastructure' },
	{ label: 'ELK', cn: 'Devops' },
	{ label: 'Grafana', cn: 'Devops' },
	{ label: 'Terraform', cn: 'Devops' },
	{ label: 'IOS', cn: 'Mobile' },
	{ label: 'Swift', cn: 'Mobile' },
	{ label: 'Flutter', cn: 'Mobile' },
	{ label: 'Next.JS', cn: 'Frontend' },
	{ label: 'React.JS', cn: 'Frontend' },
	{ label: 'Javascript', cn: 'Frontend' },
	{ label: 'Balsamic', cn: 'UX/UI' },
	{ label: 'Invision', cn: 'UX/UI' },
	{ label: 'Figma', cn: 'UX/UI' },
	{ label: 'Docker', cn: 'Devops' },
	{ label: 'PostgreSQL', cn: 'Backend' },
	{ label: 'GCP', cn: 'Backend' },
	{ label: 'Node.JS', cn: 'Backend' },
	{ label: 'PHP', cn: 'Backend' },
	{ label: 'GO', cn: 'Backend' },
	{ label: 'Ant Design', cn: 'Frontend' },
	{ label: 'Next.JS', cn: 'Frontend' },
	{ label: 'Vue.JS', cn: 'Frontend' },
	{ label: 'Principle', cn: 'UX/UI' },
	{ label: 'Sketch', cn: 'UX/UI' },
	{ label: 'Adobe suite', cn: 'UX/UI' },
	{ label: 'YouTrack', cn: 'Testing' },
	{ label: 'Appium', cn: 'Testing' },
	{ label: 'Cypress', cn: 'Testing' },
	{ label: 'Jmeter', cn: 'Testing' },
	{ label: 'MongoDB', cn: 'Backend' },
	{ label: 'Cassandra', cn: 'Backend' },
	{ label: 'Sass', cn: 'Frontend' },
	{ label: 'Material UI', cn: 'Frontend' },
	{ label: 'Zeplin', cn: 'UX/UI' },
	{ label: 'Illustrator', cn: 'UX/UI' },
	{ label: 'Lottie', cn: 'UX/UI' },
	{ label: 'Photoshop', cn: 'UX/UI' },
]
